#!/usr/bin/env bash

echo Current SHELL:
echo $SHELL
if [ -n "`$SHELL -c 'echo $ZSH_VERSION'`" ]; then
   # assume Zsh
	 apt update
   echo Switching shell to ZSH.
else
  echo ZSH is not installed. Installing now...
  apt update && apt install -y zsh
fi
chsh -s $(which zsh)
