#!/usr/bin/env bash
# setup_dependencies - installs packages/services/CLIs/etc...
#
# Copyright (C) - 2022 Leo Crossman
#
# setup_dependencies

# permanently turn off analytics tracking
brew analytics off

# cowsay
if ! command -v cowsay &> /dev/null
then
	brew install cowsay
fi

# zoxide
if ! command -v zoxide &> /dev/null
then
	brew install zoxide
fi

# neovim
if ! command -v nvim &> /dev/null
then
	brew install neovim
fi

# check if `vim-plug` is installed
# this could be maintained with dotfiles, but better to get a current `plug.vim` file
if [ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim ]; then
    echo "Installing vim-plug for Neovim..."
		sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
		echo "vim-plug for Neovim installed."
fi

# install vim/neovim plugins
if [ ! -d "$HOME/.vim/plugged" ]; then
	echo Installing plugins...
	nvim +'PlugInstall --sync' +qa
	echo Plugins installed.
fi

# if ! command -v node &> /dev/null
# then

# fi

if ! command -v python3 &> /dev/null
then
	brew install python
	python3 -m pip install --user --upgrade pynvim
fi

if ! command -v tmux &> /dev/null
then
	brew install tmux
fi

# install tpm (tmux plugin manager)
if [ ! -d "$HOME/.tmux/plugins/tpm/" ]; then
	echo Installing tpm...
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
	echo tpm installed.
fi

if ! command -v htop &> /dev/null
then
	brew install htop
fi

if ! command -v rustup &> /dev/null
then
  curl https://sh.rustup.rs -sSf | sh
fi

if ! command -v fzf &> /dev/null
then
  brew install fzf
  # To install useful key bindings and fuzzy completion:
  $(brew --prefix)/opt/fzf/install
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-nvm" ]; then
  git clone https://github.com/lukechilds/zsh-nvm ~/.oh-my-zsh/custom/plugins/zsh-nvm
fi
