#!/usr/bin/env bash
# setup_dependencies - installs packages/services/CLIs/etc...
#
# Copyright (C) - 2022 Leo Crossman
#
# setup_dependencies

# permanently turn off analytics tracking
brew analytics off

# cowsay
if ! command -v cowsay &> /dev/null
then
	brew install cowsay
fi

# zoxide
if ! command -v zoxide &> /dev/null
then
	brew install zoxide
fi

# neovim
if ! command -v nvim &> /dev/null
then
	brew install neovim
fi

# check if `vim-plug` is installed
# this could be maintained with dotfiles, but better to get a current `plug.vim` file
if [ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim ]; then
    echo "Installing vim-plug for Neovim..."
		sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
		echo "`vim-plug` for Neovim installed."
fi

# install vim/neovim plugins
if [ ! -d "$HOME/.vim/plugged" ]; then
	echo Installing plugins...
	nvim +'PlugInstall --sync' +qa
	echo Plugins installed.
fi

# if ! command -v node &> /dev/null
# then

# fi

if ! command -v python3 &> /dev/null
then
	brew install python
	python3 -m pip install --user --upgrade pynvim
fi

if ! command -v tmux &> /dev/null
then
	brew install tmux
fi

