#!/usr/bin/env bash
# commit all files/changes nested in ~/.config as specified below:

dot="/usr/bin/git --git-dir=/home/${USER}/dotfiles.git --work-tree=/home/${USER}"

# Hides all the untracked files in the output
$dot config --local status.showUntrackedFiles no

###### add all changes made to tracked files
$dot add -u

###### nvim
$dot add $HOME/.config/nvim
# $dot commit -m "nightly nvim"
# $dot push

###### coc (nvim code completion)
$dot add $HOME/.config/coc
# $dot commit -m "nightly coc"
# $dot push

$dot commit -m "nightly"
$dot push
